init:function(t){this.addElement("info-link","info-close");this.append({info:["info-link","info-close"]});var w=this.$("info-link,info-close,info-text"),R=Galleria.TOUCH,M=R?"touchstart":"click";this.$("loader,counter").show().css("opacity",0.4);if(!R){this.addIdleState(this.get("image-nav-left"),{left:-50});this.addIdleState(this.get("image-nav-right"),{right:-50});this.addIdleState(this.get("counter"),{opacity:0})}if(t._toggleInfo===true)w.bind(M,function(){w.toggle()});else{w.show();this.$("info-link, info-close").hide()}this.bind("thumbnail",
function(N){if(R)j(N.thumbTarget).css("opacity",N.index==t.show?1:0.6);else{j(N.thumbTarget).css("opacity",0.6).parent().hover(function(){j(this).not(".active").children().stop().fadeTo(100,1)},function(){j(this).not(".active").children().stop().fadeTo(400,0.6)});N.index===t.show&&j(N.thumbTarget).css("opacity",1)}});this.bind("loadstart",function(N){N.cached||this.$("loader").show().fadeTo(200,0.4);this.$("info").toggle(this.hasInfo());j(N.thumbTarget).css("opacity",1).parent().siblings().children().css("opacity",
0.6)});this.bind("loadfinish",function(){this.$("loader").fadeOut(200)})}});G.make(4,{defaults:{transition:"pulse",thumbCrop:"width",imageCrop:false,carousel:false,show:false,easing:"galleriaOut",fullscreenDoubleTap:false,_webkitCursor:true,_animate:true},init:function(t){this.addElement("preloader","loaded","close").append({container:"preloader",preloader:"loaded",stage:"close"});var w=this,R=this.$("stage"),M=this.$("thumbnails"),N=this.$("images"),W=this.$("info"),da=this.$("loader"),aa=this.$("target"),
ca=0,X=aa.width(),P=0,ia=t.show,ja=false,la=function($){w.$("info").css({left:Math.max(20,j(window).width()/2-$/2+10)})},d=function($,ea){ea=j.extend({speed:400,width:190,onbrick:function(){},onheight:function(){},delay:0,debug:false},ea);$=j($);var A=$.children(),fa=$.width(),qa=Math.floor(fa/ea.width),ka=[],q,ra,c;fa={"float":"none",position:"absolute",display:j.browser.safari?"inline-block":"block"};if($.data("colCount")!==qa){$.data("colCount",qa);if(A.length){for(q=0;q<qa;q++)ka[q]=0;$.css("position",
"relative");A.css(fa).each(function(i,n){n=j(n);for(q=qa-1;q>-1;q--)if(ka[q]===Math.min.apply(window,ka))ra=q;c={top:ka[ra],left:ea.width*ra};if(!(typeof c.top!=="number"||typeof c.left!=="number")){if(ea.speed)window.setTimeout(function(k,s,C){return function(){Galleria.utils.animate(k,C,{easing:"galleriaOut",duration:s.speed,complete:s.onbrick})}}(n,ea,c),i*ea.delay);else{n.css(c);ea.onbrick.call(n)}n.data("height")||n.data("height",n.outerHeight(true));ka[ra]+=n.data("height")}});A=Math.max.apply(window,
ka);if(!(A<0))if(typeof A==="number")if(ea.speed)$.animate({height:Math.max.apply(window,ka)},ea.speed,ea.onheight);else{$.height(Math.max.apply(window,ka));ea.onheight.call($)}}}};Galleria.OPERA&&this.$("stage").css("display","none");this.bind("fullscreen_enter",function(){N.css("visibility","hidden");R.show();this.$("container").css("height","100%");ja=true});this.bind("fullscreen_exit",function(){R.hide();M.show();W.hide();ja=false});this.bind("thumbnail",function($){this.addElement("plus");var ea=
$.thumbTarget,A=this.$("plus").css({display:"block"}).insertAfter(ea),fa=j(ea).parent().data("index",$.index);t.showInfo&&this.hasInfo($.index)&&A.append("<span>"+this.getData($.index).title+"</span>");P=P||j(ea).parent().outerWidth(true);j(ea).css("opacity",0);fa.unbind(t.thumbEventType);Galleria.IE?A.hide():A.css("opacity",0);Galleria.TOUCH?fa.bind("touchstart",function(){A.css("opacity",1)}).bind("touchend",function(){A.hide()}):fa.hover(function(){Galleria.IE?A.show():A.stop().css("opacity",1)},
function(){Galleria.IE?A.hide():A.stop().animate({opacity:0},300)});ca++;this.$("loaded").css("width",ca/this.getDataLength()*100+"%");if(ca===this.getDataLength()){this.$("preloader").fadeOut(100);d(M,{width:P,speed:t._animate?400:0,onbrick:function(){var qa=j(this).find("img");window.setTimeout(function(ka){return function(){Galleria.utils.animate(ka,{opacity:1},{duration:t.transition_speed});ka.parent().bind(Galleria.TOUCH?"mouseup":"click",function(){M.hide();W.hide();var q=j(this);w.enterFullscreen(function(){w.show(q.data("index"));
if(q.data("index")===ia){N.css("visibility","visible");W.toggle(w.hasInfo())}})})}}(qa),t._animate?qa.parent().data("index")*100:0)},onheight:function(){aa.height(M.height())}})}});this.bind("loadstart",function($){$.cached||da.show()});this.bind("loadfinish",function($){W.hide();ia=this.getIndex();N.css("visibility","visible");da.hide();if(this.hasInfo()&&t.showInfo)W.fadeIn(t.transition?t.transitionSpeed:0);la($.imageTarget.width)});if(!Galleria.TOUCH){this.addIdleState(this.get("image-nav-left"),
{left:-100});this.addIdleState(this.get("image-nav-right"),{right:-100});this.addIdleState(this.get("info"),{opacity:0});this.addIdleState(this.get("close"),{top:-50})}this.$("container").css({width:t.width,height:"auto"});t._webkitCursor&&Galleria.WEBKIT&&this.$("image-nav-right,image-nav-left").addClass("cur");if(Galleria.TOUCH){this.setOptions({transition:"fadeslide",initialTransition:false});this.$("image-nav").hide()}this.$("close").click(function(){w.exitFullscreen()});j(window).resize(function(){if(ja)w.getActiveImage()&&
la(w.getActiveImage().width);else{var $=aa.width();if($!==X){X=$;d(M,{width:P,delay:50,debug:true,onheight:function(){aa.height(M.height())}})}}})}})})(jQuery);(function(j){var t={ignoreFiles:["index.htm","index.html","index.shtml","index.cgi","index.php"],strictQuery:true,ignore:function(){return RegExp("("+this.ignoreFiles.join("|")+")","i")},window:function(){var w=window.location,R=w.href.cleanPath(this.ignore()).split("/");w=w.search.substring(1).length>0?w.search.substring(1).split("&"):[];this.strictQuery||w.sort();return R.concat(w)},anchor:function(w){var R=w.getAttribute("href",1);if(!R||w.nodeName!="A")return false;w=window.location;R=R.absUrl().cleanPath(this.ignore());
if(R===(w.protocol+"//"+w.hostname).replace(/www\./,"").noSlash())return false;w=R.split("?");R=w[0].noSlash().split("/");w=w.length>1?w[1].split("&"):[];this.strictQuery||w.sort();return R.concat(w)},compareArray:function(w,R){if(w.length!=R.length)return false;for(var M=0;M<R.length;M++)if(w[M]!==R[M])return false;return true},match:function(w){if(j(w).attr("href")=="#")return false;var R=this.anchor(w),M=this.window();if(w.pathname.split("/").length<3)return this.compareArray(M,R);return M.length<
R.length?false:this.compareArray(M.slice(0,R.length),R)},current:function(w){if(j(w).attr("href")=="#")return false;w=this.anchor(w);return this.compareArray(this.window(),w)}};j.extend(j.expr[":"],{path:function(w){return t.match(w)}});j.extend(j.expr[":"],{current:function(w){return t.current(w)}});String.prototype.noSlash=function(){return this.lastIndexOf("/")===this.length-1||this.lastIndexOf("#")===this.length-1?this.substr(0,this.length-1):this.toString()};String.prototype.absUrl=function(){var w=
window.location,R,M;if(/^\w+:/.test(this))return this.toString();R=w.protocol+"//"+w.host;if(this.indexOf("/")===0)return R+this.toString();w=w.pathname.replace(/\/[^\/]*$/,"");if(M=this.match(/\.\.\//g)){var N=this.substring(M.length*3);for(M=M.length;M--;)w=w.substring(0,w.lastIndexOf("/"))}else N=this.toString();return R+w+"/"+N};String.prototype.cleanPath=function(w){return this.replace(/www\./i,"").replace(w,"").replace(/\.\//,"").noSlash().toString()}})(jQuery);
